require("class")
require("NBTbuilder")
local function test_orient_stairs()
  local builder = NBTbuilder("MedivalStable1")
  local x,y,z = builder.blueprint:find_next_occurence("minecraft:oak_stairs", builder.iter)
  builder:go(x,y,z)
  local block = builder.blueprint:legacy_block_name(x,y,z)
  
  builder:orient({"north", "south", "west", "east"}, "west")
  print()
  builder:orient({"up", "down"}, "down")
  print()
  builder:orient({"north_up", "south_up", "west_down", "east_down", "north_down", "south_down", "west_up", "east_up"}, "south_down")
  print()
  builder:orient({"y","z","bark","x"}, "x")
end
